// Code generated by "stringer -type=TxnField,GlobalField,AssetParamsField,AppParamsField,AcctParamsField,AssetHoldingField,OnCompletionConstType,EcdsaCurve,EcGroup,MimcConfig,Base64Encoding,JSONRefType,VoterParamsField,VrfStandard,BlockField -output=fields_string.go"; DO NOT EDIT.

package logic

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Sender-0]
	_ = x[Fee-1]
	_ = x[FirstValid-2]
	_ = x[FirstValidTime-3]
	_ = x[LastValid-4]
	_ = x[Note-5]
	_ = x[Lease-6]
	_ = x[Receiver-7]
	_ = x[Amount-8]
	_ = x[CloseRemainderTo-9]
	_ = x[VotePK-10]
	_ = x[SelectionPK-11]
	_ = x[VoteFirst-12]
	_ = x[VoteLast-13]
	_ = x[VoteKeyDilution-14]
	_ = x[Type-15]
	_ = x[TypeEnum-16]
	_ = x[FeeSponsored-17]
	_ = x[Sponsor-18]
	_ = x[XferAsset-19]
	_ = x[AssetAmount-20]
	_ = x[AssetSender-21]
	_ = x[AssetReceiver-22]
	_ = x[AssetCloseTo-23]
	_ = x[GroupIndex-24]
	_ = x[TxID-25]
	_ = x[ApplicationID-26]
	_ = x[OnCompletion-27]
	_ = x[ApplicationArgs-28]
	_ = x[NumAppArgs-29]
	_ = x[Accounts-30]
	_ = x[NumAccounts-31]
	_ = x[ApprovalProgram-32]
	_ = x[ClearStateProgram-33]
	_ = x[RekeyTo-34]
	_ = x[ConfigAsset-35]
	_ = x[ConfigAssetTotal-36]
	_ = x[ConfigAssetDecimals-37]
	_ = x[ConfigAssetDefaultFrozen-38]
	_ = x[ConfigAssetUnitName-39]
	_ = x[ConfigAssetName-40]
	_ = x[ConfigAssetURL-41]
	_ = x[ConfigAssetMetadataHash-42]
	_ = x[ConfigAssetManager-43]
	_ = x[ConfigAssetReserve-44]
	_ = x[ConfigAssetFreeze-45]
	_ = x[ConfigAssetClawback-46]
	_ = x[FreezeAsset-47]
	_ = x[FreezeAssetAccount-48]
	_ = x[FreezeAssetFrozen-49]
	_ = x[Assets-50]
	_ = x[NumAssets-51]
	_ = x[Applications-52]
	_ = x[NumApplications-53]
	_ = x[GlobalNumUint-54]
	_ = x[GlobalNumByteSlice-55]
	_ = x[LocalNumUint-56]
	_ = x[LocalNumByteSlice-57]
	_ = x[ExtraProgramPages-58]
	_ = x[Nonparticipation-59]
	_ = x[Logs-60]
	_ = x[NumLogs-61]
	_ = x[CreatedAssetID-62]
	_ = x[CreatedApplicationID-63]
	_ = x[LastLog-64]
	_ = x[StateProofPK-65]
	_ = x[ApprovalProgramPages-66]
	_ = x[NumApprovalProgramPages-67]
	_ = x[ClearStateProgramPages-68]
	_ = x[NumClearStateProgramPages-69]
	_ = x[RejectVersion-70]
	_ = x[invalidTxnField-71]
}

const _TxnField_name = "SenderFeeFirstValidFirstValidTimeLastValidNoteLeaseReceiverAmountCloseRemainderToVotePKSelectionPKVoteFirstVoteLastVoteKeyDilutionTypeTypeEnumFeeSponsoredSponsorXferAssetAssetAmountAssetSenderAssetReceiverAssetCloseToGroupIndexTxIDApplicationIDOnCompletionApplicationArgsNumAppArgsAccountsNumAccountsApprovalProgramClearStateProgramRekeyToConfigAssetConfigAssetTotalConfigAssetDecimalsConfigAssetDefaultFrozenConfigAssetUnitNameConfigAssetNameConfigAssetURLConfigAssetMetadataHashConfigAssetManagerConfigAssetReserveConfigAssetFreezeConfigAssetClawbackFreezeAssetFreezeAssetAccountFreezeAssetFrozenAssetsNumAssetsApplicationsNumApplicationsGlobalNumUintGlobalNumByteSliceLocalNumUintLocalNumByteSliceExtraProgramPagesNonparticipationLogsNumLogsCreatedAssetIDCreatedApplicationIDLastLogStateProofPKApprovalProgramPagesNumApprovalProgramPagesClearStateProgramPagesNumClearStateProgramPagesRejectVersioninvalidTxnField"

var _TxnField_index = [...]uint16{0, 6, 9, 19, 33, 42, 46, 51, 59, 65, 81, 87, 98, 107, 115, 130, 134, 142, 154, 161, 170, 181, 192, 205, 217, 227, 231, 244, 256, 271, 281, 289, 300, 315, 332, 339, 350, 366, 385, 409, 428, 443, 457, 480, 498, 516, 533, 552, 563, 581, 598, 604, 613, 625, 640, 653, 671, 683, 700, 717, 733, 737, 744, 758, 778, 785, 797, 817, 840, 862, 887, 900, 915}

func (i TxnField) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TxnField_index)-1 {
		return "TxnField(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TxnField_name[_TxnField_index[idx]:_TxnField_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MinTxnFee-0]
	_ = x[MinBalance-1]
	_ = x[MaxTxnLife-2]
	_ = x[ZeroAddress-3]
	_ = x[GroupSize-4]
	_ = x[LogicSigVersion-5]
	_ = x[Round-6]
	_ = x[LatestTimestamp-7]
	_ = x[CurrentApplicationID-8]
	_ = x[CreatorAddress-9]
	_ = x[CurrentApplicationAddress-10]
	_ = x[GroupID-11]
	_ = x[OpcodeBudget-12]
	_ = x[CallerApplicationID-13]
	_ = x[CallerApplicationAddress-14]
	_ = x[AssetCreateMinBalance-15]
	_ = x[AssetOptInMinBalance-16]
	_ = x[GenesisHash-17]
	_ = x[PayoutsEnabled-18]
	_ = x[PayoutsGoOnlineFee-19]
	_ = x[PayoutsPercent-20]
	_ = x[PayoutsMinBalance-21]
	_ = x[PayoutsMaxBalance-22]
	_ = x[invalidGlobalField-23]
}

const _GlobalField_name = "MinTxnFeeMinBalanceMaxTxnLifeZeroAddressGroupSizeLogicSigVersionRoundLatestTimestampCurrentApplicationIDCreatorAddressCurrentApplicationAddressGroupIDOpcodeBudgetCallerApplicationIDCallerApplicationAddressAssetCreateMinBalanceAssetOptInMinBalanceGenesisHashPayoutsEnabledPayoutsGoOnlineFeePayoutsPercentPayoutsMinBalancePayoutsMaxBalanceinvalidGlobalField"

var _GlobalField_index = [...]uint16{0, 9, 19, 29, 40, 49, 64, 69, 84, 104, 118, 143, 150, 162, 181, 205, 226, 246, 257, 271, 289, 303, 320, 337, 355}

func (i GlobalField) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_GlobalField_index)-1 {
		return "GlobalField(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GlobalField_name[_GlobalField_index[idx]:_GlobalField_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AssetTotal-0]
	_ = x[AssetDecimals-1]
	_ = x[AssetDefaultFrozen-2]
	_ = x[AssetUnitName-3]
	_ = x[AssetName-4]
	_ = x[AssetURL-5]
	_ = x[AssetMetadataHash-6]
	_ = x[AssetManager-7]
	_ = x[AssetReserve-8]
	_ = x[AssetFreeze-9]
	_ = x[AssetClawback-10]
	_ = x[AssetCreator-11]
	_ = x[invalidAssetParamsField-12]
}

const _AssetParamsField_name = "AssetTotalAssetDecimalsAssetDefaultFrozenAssetUnitNameAssetNameAssetURLAssetMetadataHashAssetManagerAssetReserveAssetFreezeAssetClawbackAssetCreatorinvalidAssetParamsField"

var _AssetParamsField_index = [...]uint8{0, 10, 23, 41, 54, 63, 71, 88, 100, 112, 123, 136, 148, 171}

func (i AssetParamsField) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AssetParamsField_index)-1 {
		return "AssetParamsField(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AssetParamsField_name[_AssetParamsField_index[idx]:_AssetParamsField_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AppApprovalProgram-0]
	_ = x[AppClearStateProgram-1]
	_ = x[AppGlobalNumUint-2]
	_ = x[AppGlobalNumByteSlice-3]
	_ = x[AppLocalNumUint-4]
	_ = x[AppLocalNumByteSlice-5]
	_ = x[AppExtraProgramPages-6]
	_ = x[AppCreator-7]
	_ = x[AppAddress-8]
	_ = x[AppVersion-9]
	_ = x[AppSizeSponsor-10]
	_ = x[invalidAppParamsField-11]
}

const _AppParamsField_name = "AppApprovalProgramAppClearStateProgramAppGlobalNumUintAppGlobalNumByteSliceAppLocalNumUintAppLocalNumByteSliceAppExtraProgramPagesAppCreatorAppAddressAppVersionAppSizeSponsorinvalidAppParamsField"

var _AppParamsField_index = [...]uint8{0, 18, 38, 54, 75, 90, 110, 130, 140, 150, 160, 174, 195}

func (i AppParamsField) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AppParamsField_index)-1 {
		return "AppParamsField(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AppParamsField_name[_AppParamsField_index[idx]:_AppParamsField_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AcctBalance-0]
	_ = x[AcctMinBalance-1]
	_ = x[AcctAuthAddr-2]
	_ = x[AcctTotalNumUint-3]
	_ = x[AcctTotalNumByteSlice-4]
	_ = x[AcctTotalExtraAppPages-5]
	_ = x[AcctTotalAppsCreated-6]
	_ = x[AcctTotalAppsOptedIn-7]
	_ = x[AcctTotalAssetsCreated-8]
	_ = x[AcctTotalAssets-9]
	_ = x[AcctTotalBoxes-10]
	_ = x[AcctTotalBoxBytes-11]
	_ = x[AcctIncentiveEligible-12]
	_ = x[AcctLastProposed-13]
	_ = x[AcctLastHeartbeat-14]
	_ = x[invalidAcctParamsField-15]
}

const _AcctParamsField_name = "AcctBalanceAcctMinBalanceAcctAuthAddrAcctTotalNumUintAcctTotalNumByteSliceAcctTotalExtraAppPagesAcctTotalAppsCreatedAcctTotalAppsOptedInAcctTotalAssetsCreatedAcctTotalAssetsAcctTotalBoxesAcctTotalBoxBytesAcctIncentiveEligibleAcctLastProposedAcctLastHeartbeatinvalidAcctParamsField"

var _AcctParamsField_index = [...]uint16{0, 11, 25, 37, 53, 74, 96, 116, 136, 158, 173, 187, 204, 225, 241, 258, 280}

func (i AcctParamsField) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AcctParamsField_index)-1 {
		return "AcctParamsField(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AcctParamsField_name[_AcctParamsField_index[idx]:_AcctParamsField_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AssetBalance-0]
	_ = x[AssetFrozen-1]
	_ = x[invalidAssetHoldingField-2]
}

const _AssetHoldingField_name = "AssetBalanceAssetFrozeninvalidAssetHoldingField"

var _AssetHoldingField_index = [...]uint8{0, 12, 23, 47}

func (i AssetHoldingField) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AssetHoldingField_index)-1 {
		return "AssetHoldingField(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AssetHoldingField_name[_AssetHoldingField_index[idx]:_AssetHoldingField_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoOp-0]
	_ = x[OptIn-1]
	_ = x[CloseOut-2]
	_ = x[ClearState-3]
	_ = x[UpdateApplication-4]
	_ = x[DeleteApplication-5]
}

const _OnCompletionConstType_name = "NoOpOptInCloseOutClearStateUpdateApplicationDeleteApplication"

var _OnCompletionConstType_index = [...]uint8{0, 4, 9, 17, 27, 44, 61}

func (i OnCompletionConstType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_OnCompletionConstType_index)-1 {
		return "OnCompletionConstType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OnCompletionConstType_name[_OnCompletionConstType_index[idx]:_OnCompletionConstType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Secp256k1-0]
	_ = x[Secp256r1-1]
	_ = x[invalidEcdsaCurve-2]
}

const _EcdsaCurve_name = "Secp256k1Secp256r1invalidEcdsaCurve"

var _EcdsaCurve_index = [...]uint8{0, 9, 18, 35}

func (i EcdsaCurve) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_EcdsaCurve_index)-1 {
		return "EcdsaCurve(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EcdsaCurve_name[_EcdsaCurve_index[idx]:_EcdsaCurve_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BN254g1-0]
	_ = x[BN254g2-1]
	_ = x[BLS12_381g1-2]
	_ = x[BLS12_381g2-3]
	_ = x[invalidEcGroup-4]
}

const _EcGroup_name = "BN254g1BN254g2BLS12_381g1BLS12_381g2invalidEcGroup"

var _EcGroup_index = [...]uint8{0, 7, 14, 25, 36, 50}

func (i EcGroup) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_EcGroup_index)-1 {
		return "EcGroup(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EcGroup_name[_EcGroup_index[idx]:_EcGroup_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BN254Mp110-0]
	_ = x[BLS12_381Mp111-1]
	_ = x[invalidMimcConfig-2]
}

const _MimcConfig_name = "BN254Mp110BLS12_381Mp111invalidMimcConfig"

var _MimcConfig_index = [...]uint8{0, 10, 24, 41}

func (i MimcConfig) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_MimcConfig_index)-1 {
		return "MimcConfig(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MimcConfig_name[_MimcConfig_index[idx]:_MimcConfig_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[URLEncoding-0]
	_ = x[StdEncoding-1]
	_ = x[invalidBase64Encoding-2]
}

const _Base64Encoding_name = "URLEncodingStdEncodinginvalidBase64Encoding"

var _Base64Encoding_index = [...]uint8{0, 11, 22, 43}

func (i Base64Encoding) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Base64Encoding_index)-1 {
		return "Base64Encoding(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Base64Encoding_name[_Base64Encoding_index[idx]:_Base64Encoding_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[JSONString-0]
	_ = x[JSONUint64-1]
	_ = x[JSONObject-2]
	_ = x[invalidJSONRefType-3]
}

const _JSONRefType_name = "JSONStringJSONUint64JSONObjectinvalidJSONRefType"

var _JSONRefType_index = [...]uint8{0, 10, 20, 30, 48}

func (i JSONRefType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_JSONRefType_index)-1 {
		return "JSONRefType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _JSONRefType_name[_JSONRefType_index[idx]:_JSONRefType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VoterBalance-0]
	_ = x[VoterIncentiveEligible-1]
	_ = x[invalidVoterParamsField-2]
}

const _VoterParamsField_name = "VoterBalanceVoterIncentiveEligibleinvalidVoterParamsField"

var _VoterParamsField_index = [...]uint8{0, 12, 34, 57}

func (i VoterParamsField) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_VoterParamsField_index)-1 {
		return "VoterParamsField(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VoterParamsField_name[_VoterParamsField_index[idx]:_VoterParamsField_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VrfAlgorand-0]
	_ = x[invalidVrfStandard-1]
}

const _VrfStandard_name = "VrfAlgorandinvalidVrfStandard"

var _VrfStandard_index = [...]uint8{0, 11, 29}

func (i VrfStandard) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_VrfStandard_index)-1 {
		return "VrfStandard(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VrfStandard_name[_VrfStandard_index[idx]:_VrfStandard_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BlkSeed-0]
	_ = x[BlkTimestamp-1]
	_ = x[BlkProposer-2]
	_ = x[BlkFeesCollected-3]
	_ = x[BlkBonus-4]
	_ = x[BlkBranch-5]
	_ = x[BlkFeeSink-6]
	_ = x[BlkProtocol-7]
	_ = x[BlkTxnCounter-8]
	_ = x[BlkProposerPayout-9]
	_ = x[BlkBranch512-10]
	_ = x[BlkSha512_256TxnCommitment-11]
	_ = x[BlkSha256TxnCommitment-12]
	_ = x[BlkSha512TxnCommitment-13]
	_ = x[invalidBlockField-14]
}

const _BlockField_name = "BlkSeedBlkTimestampBlkProposerBlkFeesCollectedBlkBonusBlkBranchBlkFeeSinkBlkProtocolBlkTxnCounterBlkProposerPayoutBlkBranch512BlkSha512_256TxnCommitmentBlkSha256TxnCommitmentBlkSha512TxnCommitmentinvalidBlockField"

var _BlockField_index = [...]uint8{0, 7, 19, 30, 46, 54, 63, 73, 84, 97, 114, 126, 152, 174, 196, 213}

func (i BlockField) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_BlockField_index)-1 {
		return "BlockField(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BlockField_name[_BlockField_index[idx]:_BlockField_index[idx+1]]
}
