name: "codegen verification"
on:
  push:
    branches:
      - master
  pull_request:

env:
  SKIP_GO_INSTALLATION: True
jobs:
  codegen_verification:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: ./.github/actions/setup-go
      - name: Setup test environment
        uses: ./.github/actions/setup-test
      - name: Run codegen_verification.sh
        run: |
          scripts/travis/codegen_verification.sh
      - name: Slack Notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST --data-urlencode "payload={\"text\": \"Codegen verification failed. ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} \"}" $SLACK_WEBHOOK_URL
        if: ${{ failure() && (contains(github.ref_name, 'rel/nightly') || contains(github.ref_name, 'rel/beta') || contains(github.ref_name, 'rel/stable') || contains(github.ref_name, 'master')) }}
